# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(500, 580)
        MainWindow.setMinimumSize(QtCore.QSize(500, 580))
        MainWindow.setMaximumSize(QtCore.QSize(500, 640))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/Bus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_commands = QtGui.QFrame(self.centralWidget)
        self.frame_commands.setMinimumSize(QtCore.QSize(482, 40))
        self.frame_commands.setMaximumSize(QtCore.QSize(482, 40))
        self.frame_commands.setFrameShape(QtGui.QFrame.Box)
        self.frame_commands.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_commands.setObjectName(_fromUtf8("frame_commands"))
        self.layoutWidget = QtGui.QWidget(self.frame_commands)
        self.layoutWidget.setGeometry(QtCore.QRect(5, 6, 482, 26))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayoutCmds = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayoutCmds.setMargin(11)
        self.gridLayoutCmds.setSpacing(6)
        self.gridLayoutCmds.setObjectName(_fromUtf8("gridLayoutCmds"))
        self.cmbModbusMode = QtGui.QComboBox(self.layoutWidget)
        self.cmbModbusMode.setMinimumSize(QtCore.QSize(0, 24))
        self.cmbModbusMode.setObjectName(_fromUtf8("cmbModbusMode"))
        self.cmbModbusMode.addItem(_fromUtf8(""))
        self.cmbModbusMode.addItem(_fromUtf8(""))
        self.gridLayoutCmds.addWidget(self.cmbModbusMode, 0, 2, 1, 1)
        self.lblModbusMode = QtGui.QLabel(self.layoutWidget)
        self.lblModbusMode.setObjectName(_fromUtf8("lblModbusMode"))
        self.gridLayoutCmds.addWidget(self.lblModbusMode, 0, 1, 1, 1)
        self.lblSlave = QtGui.QLabel(self.layoutWidget)
        self.lblSlave.setObjectName(_fromUtf8("lblSlave"))
        self.gridLayoutCmds.addWidget(self.lblSlave, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutCmds.addItem(spacerItem, 0, 7, 1, 1)
        self.btStartStop = QtGui.QPushButton(self.layoutWidget)
        self.btStartStop.setMinimumSize(QtCore.QSize(0, 24))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/plug-disconnect-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/plug-connect-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btStartStop.setIcon(icon1)
        self.btStartStop.setIconSize(QtCore.QSize(16, 16))
        self.btStartStop.setCheckable(True)
        self.btStartStop.setObjectName(_fromUtf8("btStartStop"))
        self.gridLayoutCmds.addWidget(self.btStartStop, 0, 0, 1, 1)
        self.spInterval = QtGui.QSpinBox(self.layoutWidget)
        self.spInterval.setMinimumSize(QtCore.QSize(0, 24))
        self.spInterval.setMinimum(1000)
        self.spInterval.setMaximum(10000)
        self.spInterval.setSingleStep(500)
        self.spInterval.setProperty("value", 5000)
        self.spInterval.setObjectName(_fromUtf8("spInterval"))
        self.gridLayoutCmds.addWidget(self.spInterval, 0, 6, 1, 1)
        self.lblSimCycle = QtGui.QLabel(self.layoutWidget)
        self.lblSimCycle.setObjectName(_fromUtf8("lblSimCycle"))
        self.gridLayoutCmds.addWidget(self.lblSimCycle, 0, 5, 1, 1)
        self.sbSlaveID = QtGui.QSpinBox(self.layoutWidget)
        self.sbSlaveID.setMinimumSize(QtCore.QSize(0, 24))
        self.sbSlaveID.setMinimum(1)
        self.sbSlaveID.setMaximum(255)
        self.sbSlaveID.setObjectName(_fromUtf8("sbSlaveID"))
        self.gridLayoutCmds.addWidget(self.sbSlaveID, 0, 4, 1, 1)
        self.verticalLayout.addWidget(self.frame_commands)
        self.tabIOs = QtGui.QTabWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabIOs.sizePolicy().hasHeightForWidth())
        self.tabIOs.setSizePolicy(sizePolicy)
        self.tabIOs.setMinimumSize(QtCore.QSize(0, 0))
        self.tabIOs.setObjectName(_fromUtf8("tabIOs"))
        self.tabCoils = QtGui.QWidget()
        self.tabCoils.setObjectName(_fromUtf8("tabCoils"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tabCoils)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(6, 5, 461, 391))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pbResetDO = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pbResetDO.setMinimumSize(QtCore.QSize(48, 0))
        self.pbResetDO.setMaximumSize(QtCore.QSize(48, 16777215))
        self.pbResetDO.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/edit-clear-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbResetDO.setIcon(icon2)
        self.pbResetDO.setObjectName(_fromUtf8("pbResetDO"))
        self.horizontalLayout.addWidget(self.pbResetDO)
        self.lblCoilsStartAddr = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblCoilsStartAddr.setObjectName(_fromUtf8("lblCoilsStartAddr"))
        self.horizontalLayout.addWidget(self.lblCoilsStartAddr)
        self.sbCoilsStartAddr = QtGui.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCoilsStartAddr.sizePolicy().hasHeightForWidth())
        self.sbCoilsStartAddr.setSizePolicy(sizePolicy)
        self.sbCoilsStartAddr.setMinimumSize(QtCore.QSize(50, 0))
        self.sbCoilsStartAddr.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbCoilsStartAddr.setMinimum(0)
        self.sbCoilsStartAddr.setMaximum(65535)
        self.sbCoilsStartAddr.setSingleStep(10)
        self.sbCoilsStartAddr.setProperty("value", 0)
        self.sbCoilsStartAddr.setObjectName(_fromUtf8("sbCoilsStartAddr"))
        self.horizontalLayout.addWidget(self.sbCoilsStartAddr)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.sbNoOfCoils = QtGui.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbNoOfCoils.sizePolicy().hasHeightForWidth())
        self.sbNoOfCoils.setSizePolicy(sizePolicy)
        self.sbNoOfCoils.setMinimumSize(QtCore.QSize(50, 0))
        self.sbNoOfCoils.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbNoOfCoils.setMinimum(1)
        self.sbNoOfCoils.setMaximum(500)
        self.sbNoOfCoils.setSingleStep(10)
        self.sbNoOfCoils.setProperty("value", 50)
        self.sbNoOfCoils.setObjectName(_fromUtf8("sbNoOfCoils"))
        self.horizontalLayout.addWidget(self.sbNoOfCoils)
        self.chkSimCoils = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.chkSimCoils.setObjectName(_fromUtf8("chkSimCoils"))
        self.horizontalLayout.addWidget(self.chkSimCoils)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tvCoilsData = QtGui.QTableView(self.verticalLayoutWidget)
        self.tvCoilsData.setMinimumSize(QtCore.QSize(450, 330))
        self.tvCoilsData.setObjectName(_fromUtf8("tvCoilsData"))
        self.tvCoilsData.horizontalHeader().setVisible(False)
        self.tvCoilsData.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tvCoilsData)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/DO.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabIOs.addTab(self.tabCoils, icon3, _fromUtf8(""))
        self.tabDiscreteInputs = QtGui.QWidget()
        self.tabDiscreteInputs.setObjectName(_fromUtf8("tabDiscreteInputs"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tabDiscreteInputs)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(6, 5, 461, 391))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pbResetDI = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pbResetDI.setMinimumSize(QtCore.QSize(48, 0))
        self.pbResetDI.setMaximumSize(QtCore.QSize(48, 16777215))
        self.pbResetDI.setText(_fromUtf8(""))
        self.pbResetDI.setIcon(icon2)
        self.pbResetDI.setObjectName(_fromUtf8("pbResetDI"))
        self.horizontalLayout_2.addWidget(self.pbResetDI)
        self.lblDigInputsStartAddr = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblDigInputsStartAddr.setObjectName(_fromUtf8("lblDigInputsStartAddr"))
        self.horizontalLayout_2.addWidget(self.lblDigInputsStartAddr)
        self.sbDigInputsstartAddr = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbDigInputsstartAddr.sizePolicy().hasHeightForWidth())
        self.sbDigInputsstartAddr.setSizePolicy(sizePolicy)
        self.sbDigInputsstartAddr.setMinimumSize(QtCore.QSize(50, 0))
        self.sbDigInputsstartAddr.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbDigInputsstartAddr.setMinimum(0)
        self.sbDigInputsstartAddr.setMaximum(65535)
        self.sbDigInputsstartAddr.setSingleStep(10)
        self.sbDigInputsstartAddr.setProperty("value", 0)
        self.sbDigInputsstartAddr.setObjectName(_fromUtf8("sbDigInputsstartAddr"))
        self.horizontalLayout_2.addWidget(self.sbDigInputsstartAddr)
        self.lblNoOfDigInputs = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblNoOfDigInputs.setObjectName(_fromUtf8("lblNoOfDigInputs"))
        self.horizontalLayout_2.addWidget(self.lblNoOfDigInputs)
        self.sbNoOfDigInputs = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbNoOfDigInputs.sizePolicy().hasHeightForWidth())
        self.sbNoOfDigInputs.setSizePolicy(sizePolicy)
        self.sbNoOfDigInputs.setMinimumSize(QtCore.QSize(50, 0))
        self.sbNoOfDigInputs.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbNoOfDigInputs.setMinimum(1)
        self.sbNoOfDigInputs.setMaximum(500)
        self.sbNoOfDigInputs.setSingleStep(10)
        self.sbNoOfDigInputs.setProperty("value", 50)
        self.sbNoOfDigInputs.setObjectName(_fromUtf8("sbNoOfDigInputs"))
        self.horizontalLayout_2.addWidget(self.sbNoOfDigInputs)
        self.chkSimDisInputs = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.chkSimDisInputs.setObjectName(_fromUtf8("chkSimDisInputs"))
        self.horizontalLayout_2.addWidget(self.chkSimDisInputs)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tvDiscreteInputsData = QtGui.QTableView(self.verticalLayoutWidget_2)
        self.tvDiscreteInputsData.setEnabled(True)
        self.tvDiscreteInputsData.setMinimumSize(QtCore.QSize(450, 330))
        self.tvDiscreteInputsData.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tvDiscreteInputsData.setObjectName(_fromUtf8("tvDiscreteInputsData"))
        self.tvDiscreteInputsData.horizontalHeader().setVisible(False)
        self.tvDiscreteInputsData.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tvDiscreteInputsData)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/DI.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabIOs.addTab(self.tabDiscreteInputs, icon4, _fromUtf8(""))
        self.tabInputRegisters = QtGui.QWidget()
        self.tabInputRegisters.setObjectName(_fromUtf8("tabInputRegisters"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.tabInputRegisters)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(6, 5, 461, 391))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setMargin(11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pbResetAI = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pbResetAI.setMinimumSize(QtCore.QSize(48, 0))
        self.pbResetAI.setMaximumSize(QtCore.QSize(48, 16777215))
        self.pbResetAI.setText(_fromUtf8(""))
        self.pbResetAI.setIcon(icon2)
        self.pbResetAI.setObjectName(_fromUtf8("pbResetAI"))
        self.horizontalLayout_4.addWidget(self.pbResetAI)
        self.lblInputRegsStartAddr = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.lblInputRegsStartAddr.setObjectName(_fromUtf8("lblInputRegsStartAddr"))
        self.horizontalLayout_4.addWidget(self.lblInputRegsStartAddr)
        self.sbInputRegsStartAddr = QtGui.QSpinBox(self.verticalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbInputRegsStartAddr.sizePolicy().hasHeightForWidth())
        self.sbInputRegsStartAddr.setSizePolicy(sizePolicy)
        self.sbInputRegsStartAddr.setMinimumSize(QtCore.QSize(50, 0))
        self.sbInputRegsStartAddr.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbInputRegsStartAddr.setMinimum(0)
        self.sbInputRegsStartAddr.setMaximum(65535)
        self.sbInputRegsStartAddr.setSingleStep(10)
        self.sbInputRegsStartAddr.setProperty("value", 0)
        self.sbInputRegsStartAddr.setObjectName(_fromUtf8("sbInputRegsStartAddr"))
        self.horizontalLayout_4.addWidget(self.sbInputRegsStartAddr)
        self.lblNoOfInputRegs = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.lblNoOfInputRegs.setObjectName(_fromUtf8("lblNoOfInputRegs"))
        self.horizontalLayout_4.addWidget(self.lblNoOfInputRegs)
        self.sbNoOfInputRegs = QtGui.QSpinBox(self.verticalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbNoOfInputRegs.sizePolicy().hasHeightForWidth())
        self.sbNoOfInputRegs.setSizePolicy(sizePolicy)
        self.sbNoOfInputRegs.setMinimumSize(QtCore.QSize(50, 0))
        self.sbNoOfInputRegs.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbNoOfInputRegs.setMinimum(1)
        self.sbNoOfInputRegs.setMaximum(500)
        self.sbNoOfInputRegs.setSingleStep(10)
        self.sbNoOfInputRegs.setProperty("value", 50)
        self.sbNoOfInputRegs.setObjectName(_fromUtf8("sbNoOfInputRegs"))
        self.horizontalLayout_4.addWidget(self.sbNoOfInputRegs)
        self.chkSimInputRegs = QtGui.QCheckBox(self.verticalLayoutWidget_4)
        self.chkSimInputRegs.setObjectName(_fromUtf8("chkSimInputRegs"))
        self.horizontalLayout_4.addWidget(self.chkSimInputRegs)
        self.cmbInputRegsType = QtGui.QComboBox(self.verticalLayoutWidget_4)
        self.cmbInputRegsType.setMaxVisibleItems(2)
        self.cmbInputRegsType.setObjectName(_fromUtf8("cmbInputRegsType"))
        self.cmbInputRegsType.addItem(_fromUtf8(""))
        self.cmbInputRegsType.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.cmbInputRegsType)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.tvInputRegistersData = QtGui.QTableView(self.verticalLayoutWidget_4)
        self.tvInputRegistersData.setMinimumSize(QtCore.QSize(450, 330))
        self.tvInputRegistersData.setObjectName(_fromUtf8("tvInputRegistersData"))
        self.tvInputRegistersData.horizontalHeader().setVisible(False)
        self.tvInputRegistersData.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.tvInputRegistersData)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/AI.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabIOs.addTab(self.tabInputRegisters, icon5, _fromUtf8(""))
        self.tabHoldingRegisters = QtGui.QWidget()
        self.tabHoldingRegisters.setObjectName(_fromUtf8("tabHoldingRegisters"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.tabHoldingRegisters)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(6, 5, 461, 391))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pbResetAO = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.pbResetAO.setMinimumSize(QtCore.QSize(48, 0))
        self.pbResetAO.setMaximumSize(QtCore.QSize(48, 16777215))
        self.pbResetAO.setText(_fromUtf8(""))
        self.pbResetAO.setIcon(icon2)
        self.pbResetAO.setObjectName(_fromUtf8("pbResetAO"))
        self.horizontalLayout_3.addWidget(self.pbResetAO)
        self.lblHoldRegsStarAddr = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.lblHoldRegsStarAddr.setObjectName(_fromUtf8("lblHoldRegsStarAddr"))
        self.horizontalLayout_3.addWidget(self.lblHoldRegsStarAddr)
        self.sbHoldingRegsStartAddr = QtGui.QSpinBox(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbHoldingRegsStartAddr.sizePolicy().hasHeightForWidth())
        self.sbHoldingRegsStartAddr.setSizePolicy(sizePolicy)
        self.sbHoldingRegsStartAddr.setMinimumSize(QtCore.QSize(50, 0))
        self.sbHoldingRegsStartAddr.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbHoldingRegsStartAddr.setMinimum(0)
        self.sbHoldingRegsStartAddr.setMaximum(65535)
        self.sbHoldingRegsStartAddr.setSingleStep(10)
        self.sbHoldingRegsStartAddr.setProperty("value", 0)
        self.sbHoldingRegsStartAddr.setObjectName(_fromUtf8("sbHoldingRegsStartAddr"))
        self.horizontalLayout_3.addWidget(self.sbHoldingRegsStartAddr)
        self.lblHoldRegs = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.lblHoldRegs.setObjectName(_fromUtf8("lblHoldRegs"))
        self.horizontalLayout_3.addWidget(self.lblHoldRegs)
        self.sbNoOfHoldingRegs = QtGui.QSpinBox(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbNoOfHoldingRegs.sizePolicy().hasHeightForWidth())
        self.sbNoOfHoldingRegs.setSizePolicy(sizePolicy)
        self.sbNoOfHoldingRegs.setMinimumSize(QtCore.QSize(50, 0))
        self.sbNoOfHoldingRegs.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbNoOfHoldingRegs.setMinimum(1)
        self.sbNoOfHoldingRegs.setMaximum(500)
        self.sbNoOfHoldingRegs.setSingleStep(10)
        self.sbNoOfHoldingRegs.setProperty("value", 50)
        self.sbNoOfHoldingRegs.setObjectName(_fromUtf8("sbNoOfHoldingRegs"))
        self.horizontalLayout_3.addWidget(self.sbNoOfHoldingRegs)
        self.chkSimHoldRegs = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.chkSimHoldRegs.setObjectName(_fromUtf8("chkSimHoldRegs"))
        self.horizontalLayout_3.addWidget(self.chkSimHoldRegs)
        self.cmbHoldRegsType = QtGui.QComboBox(self.verticalLayoutWidget_3)
        self.cmbHoldRegsType.setMaxVisibleItems(2)
        self.cmbHoldRegsType.setObjectName(_fromUtf8("cmbHoldRegsType"))
        self.cmbHoldRegsType.addItem(_fromUtf8(""))
        self.cmbHoldRegsType.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cmbHoldRegsType)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tvHoldingRegistersData = QtGui.QTableView(self.verticalLayoutWidget_3)
        self.tvHoldingRegistersData.setMinimumSize(QtCore.QSize(450, 330))
        self.tvHoldingRegistersData.setObjectName(_fromUtf8("tvHoldingRegistersData"))
        self.tvHoldingRegistersData.horizontalHeader().setVisible(False)
        self.tvHoldingRegistersData.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.tvHoldingRegistersData)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/AO.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabIOs.addTab(self.tabHoldingRegisters, icon6, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabIOs)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuOptions = QtGui.QMenu(self.menuBar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuCommands = QtGui.QMenu(self.menuBar)
        self.menuCommands.setObjectName(_fromUtf8("menuCommands"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/exit-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon7)
        self.actionExit.setIconVisibleInMenu(True)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSerial_RTU = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/serial-pot-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSerial_RTU.setIcon(icon8)
        self.actionSerial_RTU.setIconVisibleInMenu(True)
        self.actionSerial_RTU.setObjectName(_fromUtf8("actionSerial_RTU"))
        self.actionTCP = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/ethernet-port-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTCP.setIcon(icon9)
        self.actionTCP.setIconVisibleInMenu(True)
        self.actionTCP.setObjectName(_fromUtf8("actionTCP"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/info-sign-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon10)
        self.actionAbout.setIconVisibleInMenu(True)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSettings = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/options-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon11)
        self.actionSettings.setIconVisibleInMenu(True)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionCoils = QtGui.QAction(MainWindow)
        self.actionCoils.setIcon(icon3)
        self.actionCoils.setObjectName(_fromUtf8("actionCoils"))
        self.actionDigital_Inputs = QtGui.QAction(MainWindow)
        self.actionDigital_Inputs.setIcon(icon4)
        self.actionDigital_Inputs.setObjectName(_fromUtf8("actionDigital_Inputs"))
        self.actionHolding_Registers = QtGui.QAction(MainWindow)
        self.actionHolding_Registers.setIcon(icon6)
        self.actionHolding_Registers.setObjectName(_fromUtf8("actionHolding_Registers"))
        self.actionAnalog_Inputs = QtGui.QAction(MainWindow)
        self.actionAnalog_Inputs.setIcon(icon5)
        self.actionAnalog_Inputs.setObjectName(_fromUtf8("actionAnalog_Inputs"))
        self.actionBus_Monitor = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/TV-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBus_Monitor.setIcon(icon12)
        self.actionBus_Monitor.setObjectName(_fromUtf8("actionBus_Monitor"))
        self.actionReset_Counters = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/reset-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReset_Counters.setIcon(icon13)
        self.actionReset_Counters.setObjectName(_fromUtf8("actionReset_Counters"))
        self.actionLog = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/text-x-log-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLog.setIcon(icon14)
        self.actionLog.setObjectName(_fromUtf8("actionLog"))
        self.actionModbus_Manual = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/help-desk-icon-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionModbus_Manual.setIcon(icon15)
        self.actionModbus_Manual.setObjectName(_fromUtf8("actionModbus_Manual"))
        self.menuFile.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionSerial_RTU)
        self.menuOptions.addAction(self.actionTCP)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionModbus_Manual)
        self.menuHelp.addAction(self.actionAbout)
        self.menuView.addAction(self.actionLog)
        self.menuView.addAction(self.actionBus_Monitor)
        self.menuView.addSeparator()
        self.menuCommands.addAction(self.actionReset_Counters)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuCommands.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.lblModbusMode.setBuddy(self.cmbModbusMode)
        self.lblSlave.setBuddy(self.sbSlaveID)

        self.retranslateUi(MainWindow)
        self.tabIOs.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Modbus Slave", None))
        self.cmbModbusMode.setItemText(0, _translate("MainWindow", "RTU", None))
        self.cmbModbusMode.setItemText(1, _translate("MainWindow", "TCP", None))
        self.lblModbusMode.setText(_translate("MainWindow", "Modbus Mode", None))
        self.lblSlave.setText(_translate("MainWindow", "Slave Addr", None))
        self.btStartStop.setToolTip(_translate("MainWindow", "Start-Stop", None))
        self.btStartStop.setText(_translate("MainWindow", "Start", None))
        self.lblSimCycle.setText(_translate("MainWindow", "Simulate Every (msec)", None))
        self.pbResetDO.setToolTip(_translate("MainWindow", "Reset", None))
        self.lblCoilsStartAddr.setText(_translate("MainWindow", "Start Addr", None))
        self.label.setText(_translate("MainWindow", "No of Coils", None))
        self.chkSimCoils.setText(_translate("MainWindow", "Sim", None))
        self.tabIOs.setTabText(self.tabIOs.indexOf(self.tabCoils), _translate("MainWindow", "Coils", None))
        self.pbResetDI.setToolTip(_translate("MainWindow", "Reset", None))
        self.lblDigInputsStartAddr.setText(_translate("MainWindow", "Start Addr", None))
        self.lblNoOfDigInputs.setText(_translate("MainWindow", "No of Inputs", None))
        self.chkSimDisInputs.setText(_translate("MainWindow", "Sim", None))
        self.tabIOs.setTabText(self.tabIOs.indexOf(self.tabDiscreteInputs), _translate("MainWindow", "Discrete Inputs", None))
        self.pbResetAI.setToolTip(_translate("MainWindow", "Reset", None))
        self.lblInputRegsStartAddr.setText(_translate("MainWindow", "Start Addr", None))
        self.lblNoOfInputRegs.setText(_translate("MainWindow", "No of Regs", None))
        self.chkSimInputRegs.setText(_translate("MainWindow", "Sim", None))
        self.cmbInputRegsType.setItemText(0, _translate("MainWindow", "Decimal", None))
        self.cmbInputRegsType.setItemText(1, _translate("MainWindow", "Hex", None))
        self.tabIOs.setTabText(self.tabIOs.indexOf(self.tabInputRegisters), _translate("MainWindow", "Input Registers", None))
        self.pbResetAO.setToolTip(_translate("MainWindow", "Reset", None))
        self.lblHoldRegsStarAddr.setText(_translate("MainWindow", "Start Addr", None))
        self.lblHoldRegs.setText(_translate("MainWindow", "No of Regs", None))
        self.chkSimHoldRegs.setText(_translate("MainWindow", "Sim", None))
        self.cmbHoldRegsType.setItemText(0, _translate("MainWindow", "Decimal", None))
        self.cmbHoldRegsType.setItemText(1, _translate("MainWindow", "Hex", None))
        self.tabIOs.setTabText(self.tabIOs.indexOf(self.tabHoldingRegisters), _translate("MainWindow", "Holding Registers", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuOptions.setTitle(_translate("MainWindow", "Options", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuCommands.setTitle(_translate("MainWindow", "Commands", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionSerial_RTU.setText(_translate("MainWindow", "Modbus RTU...", None))
        self.actionTCP.setText(_translate("MainWindow", "Modbus TCP...", None))
        self.actionAbout.setText(_translate("MainWindow", "About...", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings...", None))
        self.actionCoils.setText(_translate("MainWindow", "Coils", None))
        self.actionDigital_Inputs.setText(_translate("MainWindow", "Digital Inputs", None))
        self.actionHolding_Registers.setText(_translate("MainWindow", "Holding Registers", None))
        self.actionAnalog_Inputs.setText(_translate("MainWindow", "Analog Inputs", None))
        self.actionBus_Monitor.setText(_translate("MainWindow", "Bus Monitor", None))
        self.actionReset_Counters.setText(_translate("MainWindow", "Reset Counters", None))
        self.actionLog.setText(_translate("MainWindow", "Log", None))
        self.actionModbus_Manual.setText(_translate("MainWindow", "Modbus Manual", None))

import pyModSlaveQt_rc
