# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Projects\python\pyModSlaveQt\ui\mainwindow.ui'
#
# Created: Thu Apr 19 12:06:07 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(360, 192)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblSettings = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSettings.setFont(font)
        self.lblSettings.setObjectName(_fromUtf8("lblSettings"))
        self.verticalLayout.addWidget(self.lblSettings)
        self.gridLayoutSettings = QtGui.QGridLayout()
        self.gridLayoutSettings.setObjectName(_fromUtf8("gridLayoutSettings"))
        self.sbSlaveID = QtGui.QSpinBox(self.centralWidget)
        self.sbSlaveID.setMinimum(1)
        self.sbSlaveID.setMaximum(255)
        self.sbSlaveID.setObjectName(_fromUtf8("sbSlaveID"))
        self.gridLayoutSettings.addWidget(self.sbSlaveID, 0, 3, 1, 1)
        self.lblModbusMode = QtGui.QLabel(self.centralWidget)
        self.lblModbusMode.setObjectName(_fromUtf8("lblModbusMode"))
        self.gridLayoutSettings.addWidget(self.lblModbusMode, 0, 0, 1, 1)
        self.cmbModbusMode = QtGui.QComboBox(self.centralWidget)
        self.cmbModbusMode.setObjectName(_fromUtf8("cmbModbusMode"))
        self.cmbModbusMode.addItem(_fromUtf8(""))
        self.cmbModbusMode.addItem(_fromUtf8(""))
        self.gridLayoutSettings.addWidget(self.cmbModbusMode, 0, 1, 1, 1)
        self.lblSlaveID = QtGui.QLabel(self.centralWidget)
        self.lblSlaveID.setObjectName(_fromUtf8("lblSlaveID"))
        self.gridLayoutSettings.addWidget(self.lblSlaveID, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutSettings.addItem(spacerItem, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayoutSettings)
        self.lblCmds = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCmds.setFont(font)
        self.lblCmds.setObjectName(_fromUtf8("lblCmds"))
        self.verticalLayout.addWidget(self.lblCmds)
        self.gridLayoutCmds = QtGui.QGridLayout()
        self.gridLayoutCmds.setObjectName(_fromUtf8("gridLayoutCmds"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutCmds.addItem(spacerItem1, 0, 3, 1, 1)
        self.btStartStop = QtGui.QPushButton(self.centralWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/run-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/stop-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btStartStop.setIcon(icon)
        self.btStartStop.setIconSize(QtCore.QSize(16, 16))
        self.btStartStop.setCheckable(True)
        self.btStartStop.setObjectName(_fromUtf8("btStartStop"))
        self.gridLayoutCmds.addWidget(self.btStartStop, 0, 0, 1, 1)
        self.spInterval = QtGui.QSpinBox(self.centralWidget)
        self.spInterval.setMinimum(500)
        self.spInterval.setMaximum(10000)
        self.spInterval.setSingleStep(500)
        self.spInterval.setProperty("value", 5000)
        self.spInterval.setObjectName(_fromUtf8("spInterval"))
        self.gridLayoutCmds.addWidget(self.spInterval, 0, 2, 1, 1)
        self.lblSimCycle = QtGui.QLabel(self.centralWidget)
        self.lblSimCycle.setObjectName(_fromUtf8("lblSimCycle"))
        self.gridLayoutCmds.addWidget(self.lblSimCycle, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayoutCmds)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 360, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuOptions = QtGui.QMenu(self.menuBar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/close16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon1)
        self.actionExit.setIconVisibleInMenu(True)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSerial_RTU = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/edit-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSerial_RTU.setIcon(icon2)
        self.actionSerial_RTU.setIconVisibleInMenu(True)
        self.actionSerial_RTU.setObjectName(_fromUtf8("actionSerial_RTU"))
        self.actionTCP = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/network-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTCP.setIcon(icon3)
        self.actionTCP.setIconVisibleInMenu(True)
        self.actionTCP.setObjectName(_fromUtf8("actionTCP"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/info16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon4)
        self.actionAbout.setIconVisibleInMenu(True)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionBus_Monitor = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/view-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBus_Monitor.setIcon(icon5)
        self.actionBus_Monitor.setIconVisibleInMenu(True)
        self.actionBus_Monitor.setObjectName(_fromUtf8("actionBus_Monitor"))
        self.actionSettings = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/options-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon6)
        self.actionSettings.setIconVisibleInMenu(True)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.menuFile.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionSerial_RTU)
        self.menuOptions.addAction(self.actionTCP)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.lblModbusMode.setBuddy(self.cmbModbusMode)
        self.lblSlaveID.setBuddy(self.sbSlaveID)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Modbus Slave", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.lblModbusMode.setText(QtGui.QApplication.translate("MainWindow", "Modbus Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbModbusMode.setItemText(0, QtGui.QApplication.translate("MainWindow", "RTU", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbModbusMode.setItemText(1, QtGui.QApplication.translate("MainWindow", "TCP", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSlaveID.setText(QtGui.QApplication.translate("MainWindow", "Slave ID", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCmds.setText(QtGui.QApplication.translate("MainWindow", "Commands", None, QtGui.QApplication.UnicodeUTF8))
        self.btStartStop.setToolTip(QtGui.QApplication.translate("MainWindow", "Start-Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.btStartStop.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSimCycle.setText(QtGui.QApplication.translate("MainWindow", "Simulate Every (msec)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSerial_RTU.setText(QtGui.QApplication.translate("MainWindow", "Modbus RTU...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTCP.setText(QtGui.QApplication.translate("MainWindow", "Modbus TCP...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBus_Monitor.setText(QtGui.QApplication.translate("MainWindow", "Bus Monitor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings...", None, QtGui.QApplication.UnicodeUTF8))

import pyModSlaveQt_rc
